name: dev_push

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/laravel/dev
          eval `ssh-agent`
          ssh-add /var/www/el
          git checkout dev
          git fetch origin dev
          git reset --hard origin/dev
          chmod +x /var/www/laravel/dev/scripts/deploy.sh
          ./scripts/deploy.sh