name: dev_pr

on:
  pull_request: 
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: echo lsb_release -a n start setup env
        run: echo lsb_release -a
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: echo ls n start install deps
        run: echo ls -altr
      - uses: actions/cache@v2
        id: vendor-cache
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-vendor-
      - name: composer install
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist
      - uses: actions/cache@v2
        id: nodemod-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-nodemod-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemod-
      - name: composer install
        if: steps.nodemod-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: config proj (env, key, storage)
        run: echo starting to config
      - name: Setup env file
        run: cp .env.example .env
      - name: Setup keys
        run: php artisan key:generate
      - name: Fix perms for dirs
        run: chmod -R 777 storage bootstrap/cache
      - name: Check PHP Version
        run: php -v
      - name: build
        run: echo starting to build
      - name: npm build
        run: npm run prod
      - name: Migrate database
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: db_test
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: password
        run: php artisan migrate
      - name: test, lint, quality chk
        run: echo starting to test
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: db_test
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: password
        run: vendor/phpunit/phpunit/phpunit
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: db_test
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: password
        run: php artisan test
